tutorial and structure changes
vcristiani/galaxy-chop pull request #128
Opened 2021-02-03 12:28 UTC by ornemarioni

Porfas vean los cambios. En general acomode un poco el tutorial. Reordene los parametros de entrada de la clase galaxia en el orden de los archivos que subio Vale (Ahora son: m, x, y, z, vx, vy, vz). Acomode los test, metodos y demás de modo que siempre se trabaje en orden STARS, DARK MATTER y GAS.
@vcristiani hay un test de un metodo que no pasa. Creo que no toque nada de eso que lo afecte, pero despues dame una mano y lo vemos.

2021-02-03 12:28 UTC, ornemarioni commented
No mergeen hasta que arreglemos ese test. Ahora tiene un xfail

2021-02-03 14:11 UTC, vcristiani requested changes
Hay que controlar con mucho cuidado las modificaciones. Marqué lo que era visible para mi, pero no sé si lo de l problema del test viene dado por reordenar en todos lados lo de la masa.

2021-02-03 14:11 UTC, vcristiani commented on docs/source/tutorial.ipynb
> +    "* **J_star**: Specific angular momentum for stars."
Estan muy mezclado esto, debería estar en este orden:

"J_part = galaxy.angular_momentum().J_part\n",
"J_star = galaxy.angular_momentum().J_star"\n",
"Jr_part = galaxy.angular_momentum().Jr_part\n",
"Jr_star = galaxy.angular_momentum().Jr_star\n"

o en este orden:

"J_part = galaxy.angular_momentum().J_part\n",
"Jr_part = galaxy.angular_momentum().Jr_part\n",
"J_star = galaxy.angular_momentum().J_star"\n",
"Jr_star = galaxy.angular_momentum().Jr_star\n"

2021-02-03 14:11 UTC, vcristiani commented on galaxychop/core.py
>      J_star = uttr.ib(default=None, unit=(u.kpc * u.km / u.s))
aca tambien esta mezclado esto, como en el tutorial

2021-02-03 15:21 UTC, ornemarioni commented on docs/source/tutorial.ipynb
> +    "This tutorial is a guide to use GalaxyChop package. GalaxyChop performs the dynamical descomposition of a galaxy with tree diferent methods."
jajaj se me paso eso

2021-02-03 19:59 UTC, ornemarioni reviewed
Ahora corrijo eso y lo anterior

2021-02-03 19:59 UTC, ornemarioni commented on galaxychop/core.py
> +            del new["arr_"]
Aca no hace falta crear una nueva clase, porque ya estan dados los potenciales, es directamente self.pot_s o algo asi

2021-02-03 20:17 UTC, RafaelPignata622 commented on galaxychop/core.py
> +            del new["arr_"]
Lo pense, pero si no devuelve una clase completa entonces hay que hacer las excepciones en la documentación de que si pones el potencial devuelve una cosa y se corre de tal manera y si no pones el potencial devueve otra cosa, se HAY una manera menos "repetitiva" ... pero para la menor cantidad de modificaciones al codigo+documentación+tutorial, esa es la manera que a mí se me ocurrió más sencilla. 

Si el return de la función es un objeto instanciado con la clase galaxia, tengas o no el potencial el return tiene que ser un objeto instanciado con la clase galaxia. Y en este momento ponerse a modificar tooooodo ... no, no es momento de hacer esas cosas, así anda y la documentación tiene sentido.

2021-02-04 18:17 UTC, ornemarioni commented
listo!

2021-02-04 18:17 UTC, merged