Docu core
vcristiani/galaxy-chop pull request #135
Opened 2021-02-06 21:22 UTC by ornemarioni

2021-02-06 21:36 UTC, antotaverna commented on galaxychop/core.py
> +    """Masses"""
(m, x, y, z, vx, vy, vz ) are stellar particles. I think. @ValeCristiani ?

2021-02-06 22:01 UTC, vcristiani commented on galaxychop/core.py
> +    """Masses"""
Yes, are stellar particles.

2021-02-06 23:14 UTC, vcristiani requested changes
The documentation is generally good. There are some changes to be made in the description of some variables, and revisit the value method documentation because it does not match what the method does.

2021-02-06 23:14 UTC, vcristiani commented on galaxychop/core.py
> +        J_p : Absolute value of the projection on the xy plane of the
Again it is not an absolute value, but the quantity is positive by definition.

2021-02-06 23:14 UTC, vcristiani commented on galaxychop/core.py
> +        """
If you look at what this method does, it does not correspond to the documentation provided.

2021-02-06 23:14 UTC, vcristiani commented on docs/source/tutorial.ipynb
> +    "* **y**: Maximum value of the z-component of the normalized specific energy per bin.\n",
**z-component of normalized specific angular momentum**

2021-02-07 14:05 UTC, vcristiani approved these changes
Everything looks good

2021-02-07 14:22 UTC, RafaelPignata622 approved these changes

2021-02-07 14:24 UTC, antotaverna approved these changes

2021-02-07 14:31 UTC, merged